name: Jimmy Schementi
description: Jimmy Schementi's website
url: http://kamarules.github.io/form
markdown: kramdown
highlighter: rouge
disqus_shortname: jschementi
paginate: 5
plugins: [jekyll-paginate]
collections:
  journal:
    output: true
  photolog:
    output: false
  iron:
    output: true
